# Conclusion

Based on our analysis, time and location all significantly correlates with air pollution. We used a variety of methods such as bar chart, time series, histogram, and d3 scatter plot to explore various factors. In detail, we find the solution for the problems that we asked at the beginning:

  1. Is the air quality becoming worse from 2010 to 2019, overall and locally?
      We found the PM2.5 level decreased for about 7 percent gradually from 2010 to 2019. Locally speaking, Europe has the most significant decrease in the world while Africa and Eastern Mediterranean has a stable PM2.5 over last 10 years. Eastern Mediterranean has the highest PM2.5 level and America & Western Pacific has the lowest PM2.5 level.
      
  2. If people want to avoid air pollution, where should they choose to live?
      If relocating to another country is not a possible option, choosing rural area generally provides a lower PM2.5 level, which has ~6% lower PM2.5 level than urban area.
    `
  3. Does the air quality generally change significantly over a year?
    Not necessarily. However, from 2018 to 2019, almost all continent exhibited the highest drop in PM2.5 level over the last 10 years.
  
  4. Which place has the best air quality over the last 10 years?
    West Hemisphere including America and Western Pacific.
    
  5. If the United Nation has more funding, which places should they commit more to improve the air quality?
    Urban places of Eastern Mediterranean such as Afghanistan and Tajikistan.
  
  6. In the future, can we predict any trend for air quality based on historical data?
    Yes, we predict the air quality will be better for all continent, but based on different policy & condition over continent, the air quality change might be different.
  
Besides, the interactive graph shows the difference between developing and developed countries: compared to developing world, developed countries tend to have less PM 2.5 problems, but the problem is growing over time. 

In summary, the air quality is getting better and better, while the condition at some urban places at east hemisphere still need to be paid more attention.
    
